---
title: Hoe is je dag?
hero_image: images/banner.png
description: Bouw een stemming checker programma dat een andere reactie laat zien op basis van hoe je dag was.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - 
    title: Inleiding
  - 
    title: Startscherm
    completion:
      - engaged
  - 
    title: Maak een antwoord
  - 
    title: Meer antwoorden maken
    completion:
      - internal
  - 
    title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Delen
  - 
    title: Wat kun je verder nog doen?
