---
title: How's your day?
hero_image: images/banner.png
description: Build a mood checker program that shows a different response based on how your day was.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Start-up screen
  completion:
    - engaged
- title: Create a response
- title: Create more responses
  completion:
    - internal
- title: Quick quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
    - external
- title: Upgrade your project
- title: Share
- title: What next?
